import Head from 'next/head'
import VideoJS from '../components/videoJS'

export default function Home() {
  const VideoOptions = {
    autoPlay: false,
    controls: true,
    sources: [{
      src: "/video.mp4",
      type: "video/mp4"
    }]
  }
  return (
    <div className="VideoPlayer">
      <Head>
        <title>Video Player | @developeruche</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="video__player__main">
        <VideoJS options={VideoOptions} />
      </main>
    </div>
  )
}
